default: &default
  adapter: postgresql
  template: template0
  host: localhost

development:
  <<: *default
  database: api_test_development

test:
  <<: *default
  database: api_test_test

production:
  <<: *default
  adapter: postgresql
  database: api_test_production
